### ISSUE TITLE
PA Review: Lodgings search bar and google maps

### ISSUE THREAD

**Issue by ckim2013** [ckim2013/skybnb#21]

**Comment by debsfong** [comment]
Needs more seeds!

**Comment by debsfong** [comment]
This might be a lot of work, but you could add a district to each lodging and users can search by district. That way you can keep it in San Francisco and not have to worry about seeding in other cities.

**Comment by debsfong** [comment]
https://developers.google.com/maps/documentation/geocoding/start Good resource for getting the neighborhood. Here's an example of what it spits out; you want to take the neighborhood long_name, I believe. http://maps.googleapis.com/maps/api/geocode/json?latlng=37.7989712,-122.4035407&sensor=true

**Comment by debsfong** [comment]
Great job implementing the neighborhoods search!
